import { useState } from 'react';
import PropTypes from 'prop-types';
import festo from '../../assets/images/festo.jfif';

const projects = [
    { name: 'Smart Hiring Assistant', type: 'AI / Full stack', stack: 'React · Node.js · OpenAI', status: 'Live', color: 'from-violet-500/25 to-indigo-500/5' },
    { name: 'Hotel Booking Platform', type: 'Web application', stack: 'React · Express · MongoDB', status: 'In progress', color: 'from-sky-500/25 to-cyan-500/5' },
    { name: 'Portfolio Analytics', type: 'Data product', stack: 'React · Charts · REST APIs', status: 'Live', color: 'from-emerald-500/25 to-teal-500/5' },
];
const skills = [{ name: 'React & Frontend', value: 90 }, { name: 'Node.js & APIs', value: 84 }, { name: 'Databases', value: 78 }, { name: 'AI Integration', value: 75 }];
const certificates = [{ name: 'Responsive Web Design', issuer: 'freeCodeCamp', date: '2025', icon: 'bi-code-slash' }, { name: 'AI for Developers', issuer: 'Coursera', date: '2026', icon: 'bi-cpu' }, { name: 'JavaScript Algorithms', issuer: 'freeCodeCamp', date: '2025', icon: 'bi-braces' }];

const Hero = ({ eyebrow, title, children }) => <section className="rounded-2xl border border-[#3a3351] bg-[linear-gradient(135deg,#211c35,#121522_64%,#10121a)] p-5 shadow-xl shadow-black/10 sm:p-7"><p className="font-mono text-[11px] uppercase tracking-[0.2em] text-[#b6aaff]">{eyebrow}</p><h2 className="mt-2 max-w-2xl text-2xl font-semibold tracking-tight text-[#f4f1ff] sm:text-3xl">{title}</h2>{children}</section>;
Hero.propTypes = { eyebrow: PropTypes.string.isRequired, title: PropTypes.string.isRequired, children: PropTypes.node };

const RecruiterDashboard = ({ section }) => {
    const [projectFilter, setProjectFilter] = useState('All');
    const [sent, setSent] = useState(false);
    const [saved, setSaved] = useState(false);
    const downloadResume = () => { const url = URL.createObjectURL(new Blob(['Kabano Festo\nFull-stack Developer\nReact | Node.js | AI Integration'], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = 'Kabano-Festo-Resume.txt'; link.click(); URL.revokeObjectURL(url); };
    const visibleProjects = projectFilter === 'All' ? projects : projects.filter((project) => project.status === projectFilter);

    if (section === 'overview') return <div className="mx-auto grid max-w-7xl gap-5"><Hero eyebrow="Candidate review" title="A developer who pairs thoughtful UI with dependable systems."><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={() => setSaved(!saved)} className={`rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors ${saved ? 'bg-[#8b7bff] text-white' : 'border border-[#8b7bff]/40 bg-[#8b7bff]/10 text-[#d7d1ff] hover:bg-[#8b7bff]/20'}`}><i className={`bi ${saved ? 'bi-bookmark-check-fill' : 'bi-bookmark-plus'} mr-2`} />{saved ? 'Saved candidate' : 'Save candidate'}</button><button type="button" onClick={downloadResume} className="rounded-lg bg-[#f1eeff] px-4 py-2.5 text-sm font-semibold text-[#181425] hover:bg-white"><i className="bi bi-download mr-2" />Download resume</button></div></Hero><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Experience', '4+ years', 'building products'], ['Projects', '12', 'portfolio-ready'], ['Core skills', '18', 'verified technologies'], ['Availability', 'Open', 'for select roles']].map(([label, value, detail]) => <article key={label} className="rounded-xl border border-[#302c42] bg-[#171522] p-5"><p className="text-sm text-[#aaa3be]">{label}</p><strong className="mt-2 block text-2xl text-[#f1eeff]">{value}</strong><span className="mt-1 block text-xs text-[#79728f]">{detail}</span></article>)}</section><section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-[#302c42] bg-[#171522] p-5"><h3 className="font-semibold">Highlights</h3><div className="mt-5 grid gap-3">{['Built AI-assisted workflows that make hiring teams faster.', 'Designed responsive interfaces for high-trust user experiences.', 'Turns complex requirements into clear, maintainable products.'].map((item, index) => <div key={item} className="flex gap-3 rounded-xl bg-[#11101a] p-4 text-sm leading-6 text-[#bbb4ca]"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#8b7bff]/15 text-xs text-[#b9adff]">0{index + 1}</span>{item}</div>)}</div></article><article className="rounded-2xl border border-[#302c42] bg-[#171522] p-5"><h3 className="font-semibold">Recent work</h3><div className="mt-4 grid gap-3">{projects.slice(0, 2).map((project) => <div key={project.name} className="rounded-xl border border-[#302c42] p-3"><p className="font-medium">{project.name}</p><span className="mt-1 block text-xs text-[#918aa2]">{project.stack}</span></div>)}</div></article></section></div>;

    if (section === 'profile') return <div className="mx-auto grid max-w-5xl gap-5"><Hero eyebrow="Profile" title="Kabano Festo · Full-stack Developer"><p className="mt-3 max-w-2xl text-sm leading-6 text-[#bbb4ca]">I build useful digital products with thoughtful interfaces, scalable backend services, and a practical approach to AI.</p></Hero><section className="grid gap-5 lg:grid-cols-[220px_1fr]"><article className="rounded-2xl border border-[#302c42] bg-[#171522] p-5"><img src={festo} alt="Kabano Festo" className="aspect-square w-full rounded-xl object-cover" /><span className="mt-4 inline-flex items-center gap-2 text-xs text-[#b9adff]"><i className="bi bi-geo-alt-fill" />Kigali, Rwanda</span></article><article className="rounded-2xl border border-[#302c42] bg-[#171522] p-5 sm:p-6"><h3 className="font-semibold">About</h3><p className="mt-3 leading-7 text-[#bbb4ca]">A product-minded developer focused on creating software that feels simple to use and is built to last. Experienced across frontend systems, API design, data workflows, and AI-powered product features.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['Role preference', 'Full-stack / Frontend'], ['Work style', 'Remote or hybrid'], ['Location', 'Kigali, Rwanda'], ['Languages', 'English, Kinyarwanda']].map(([label, value]) => <div key={label} className="rounded-xl bg-[#11101a] p-4"><p className="text-xs text-[#837b96]">{label}</p><p className="mt-1 text-sm text-[#eeeaff]">{value}</p></div>)}</div></article></section></div>;

    if (section === 'projects') return <div className="mx-auto grid max-w-6xl gap-5"><Hero eyebrow="Portfolio" title="Selected work, designed around real outcomes."><div className="mt-5 flex gap-2">{['All', 'Live', 'In progress'].map((filter) => <button type="button" key={filter} onClick={() => setProjectFilter(filter)} className={`rounded-full px-3 py-1.5 text-xs transition-colors ${projectFilter === filter ? 'bg-[#8b7bff] text-white' : 'border border-[#3a3351] text-[#aaa3be] hover:text-white'}`}>{filter}</button>)}</div></Hero><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visibleProjects.map((project) => <article key={project.name} className="overflow-hidden rounded-2xl border border-[#302c42] bg-[#171522] transition-transform hover:-translate-y-1"><div className={`h-28 bg-gradient-to-br ${project.color} p-4`}><span className="rounded-full bg-black/20 px-2.5 py-1 text-xs text-white">{project.status}</span></div><div className="p-5"><p className="text-xs text-[#a99aff]">{project.type}</p><h3 className="mt-1 font-semibold">{project.name}</h3><p className="mt-3 text-sm text-[#aaa3be]">{project.stack}</p><button type="button" className="mt-5 text-sm font-medium text-[#c3b9ff] hover:text-white">View project <i className="bi bi-arrow-up-right" /></button></div></article>)}</section></div>;

    if (section === 'certificates') return <div className="mx-auto grid max-w-6xl gap-5"><Hero eyebrow="Credentials" title="Verified learning and continued growth." /><section className="grid gap-4 md:grid-cols-3">{certificates.map((certificate) => <article key={certificate.name} className="rounded-2xl border border-[#302c42] bg-[#171522] p-5"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#8b7bff]/15 text-[#b9adff]"><i className={`bi ${certificate.icon} text-lg`} /></span><h3 className="mt-5 font-semibold">{certificate.name}</h3><p className="mt-2 text-sm text-[#aaa3be]">{certificate.issuer} · {certificate.date}</p><span className="mt-5 inline-flex items-center gap-1 text-xs text-[#9af0d8]"><i className="bi bi-patch-check-fill" /> Verified</span></article>)}</section></div>;

    if (section === 'skills') return <div className="mx-auto grid max-w-6xl gap-5"><Hero eyebrow="Technical profile" title="A balanced, product-focused engineering toolkit." /><section className="grid gap-4 lg:grid-cols-2">{skills.map((skill) => <article key={skill.name} className="rounded-2xl border border-[#302c42] bg-[#171522] p-5"><div className="flex justify-between text-sm"><h3 className="font-medium">{skill.name}</h3><span className="text-[#b9adff]">{skill.value}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#292537]"><div className="h-full rounded-full bg-gradient-to-r from-[#7f70ef] to-[#b8adff]" style={{ width: `${skill.value}%` }} /></div></article>)}</section><section className="rounded-2xl border border-[#302c42] bg-[#171522] p-5"><h3 className="font-semibold">Technology stack</h3><div className="mt-4 flex flex-wrap gap-2">{['React', 'JavaScript', 'TypeScript', 'Node.js', 'Express', 'MongoDB', 'PostgreSQL', 'Git', 'REST APIs', 'OpenAI'].map((tech) => <span key={tech} className="rounded-full border border-[#3a3351] bg-[#11101a] px-3 py-1.5 text-xs text-[#c4bdd3]">{tech}</span>)}</div></section></div>;

    if (section === 'resume') return <div className="mx-auto grid max-w-5xl gap-5"><Hero eyebrow="Resume" title="A concise record of experience, skills, and impact."><button type="button" onClick={downloadResume} className="mt-5 rounded-lg bg-[#f1eeff] px-4 py-2.5 text-sm font-semibold text-[#181425]"><i className="bi bi-download mr-2" />Download resume</button></Hero><article className="rounded-2xl border border-[#302c42] bg-[#171522] p-5 sm:p-7"><div className="flex items-start justify-between gap-4 border-b border-[#302c42] pb-5"><div><h3 className="text-lg font-semibold">Kabano Festo</h3><p className="mt-1 text-sm text-[#aaa3be]">Full-stack Developer · Kigali, Rwanda</p></div><i className="bi bi-file-earmark-text text-2xl text-[#b9adff]" /></div><div className="mt-6 grid gap-6"><section><h4 className="font-mono text-xs uppercase tracking-widest text-[#b9adff]">Experience</h4><p className="mt-3 font-medium">Full-stack Developer</p><p className="mt-1 text-sm leading-6 text-[#aaa3be]">Developed responsive web applications, integrated AI features, and delivered maintainable APIs for real product needs.</p></section><section><h4 className="font-mono text-xs uppercase tracking-widest text-[#b9adff]">Education & learning</h4><p className="mt-3 text-sm leading-6 text-[#aaa3be]">Continuous learning in web development, modern JavaScript, and applied AI for developers.</p></section></div></article></div>;

    return <div className="mx-auto max-w-3xl"><Hero eyebrow="Contact" title="Start a conversation with Kabano."><p className="mt-3 text-sm text-[#bbb4ca]">Share the role, team, or collaboration you have in mind.</p></Hero><form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className="mt-5 grid gap-4 rounded-2xl border border-[#302c42] bg-[#171522] p-5 sm:p-6">{sent && <div role="status" className="rounded-lg border border-[#9af0d8]/30 bg-[#9af0d8]/10 px-4 py-3 text-sm text-[#a8f3de]">Message sent. Kabano will get back to you soon.</div>}<div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm text-[#bbb4ca]">Your name<input required className="rounded-lg border border-[#3a3351] bg-[#11101a] px-3 py-2.5 text-white outline-none focus:border-[#a99aff]" /></label><label className="grid gap-2 text-sm text-[#bbb4ca]">Work email<input required type="email" className="rounded-lg border border-[#3a3351] bg-[#11101a] px-3 py-2.5 text-white outline-none focus:border-[#a99aff]" /></label></div><label className="grid gap-2 text-sm text-[#bbb4ca]">Message<textarea required rows="5" className="resize-y rounded-lg border border-[#3a3351] bg-[#11101a] px-3 py-2.5 text-white outline-none focus:border-[#a99aff]" placeholder="Tell Kabano about the opportunity..." /></label><button type="submit" className="w-fit rounded-lg bg-[#8b7bff] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#9d90ff]"><i className="bi bi-send mr-2" />Send message</button></form></div>;
};

RecruiterDashboard.propTypes = { section: PropTypes.string.isRequired };
export default RecruiterDashboard;
